name: Build docker image

on:
  workflow_call:
    inputs:
      push:
        description: Indicates if the docker image has to be pushed
        type: boolean
        default: false
    outputs:
      image-tag:
        description: Image tag used
        value: ${{ github.event.pull_request.head.sha || github.sha }}

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Docker Build ğŸ‹
    runs-on: x1-core
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Docker build
        uses: cloudbeds/composite-actions/docker/build-push/remote@v2
        with:
          push: ${{ inputs.push }}
